### ISSUE TITLE
Add MIT LICENSE.txt file

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtsass#9]
.txt to make it windows friendly

**Comment by CAM-Gerlach** [comment]
You can base your LICENSE and AUTHORS files off the respective ones in the [Spyder docs](https://github.com/spyder-ide/spyder-docs) repo, except with 

```
Copyright (c) 2015 Yann Lanthony
Copyright (c) 2017-2018 Spyder Project Contributors
```

for the copyright, and ``Yann Lanthony`` listed (as original author) instead of Pierre and Carlos (and yourself as current maintainer, if you'd like).

**Comment by danbradham** [comment]
@yann-lty Would you like your email included in this project?

**Comment by CAM-Gerlach** [comment]
Also, more importantly, are you okay with releasing this project, including your work, under the MIT license? Right now, there is no license listed. Thanks!

**Comment by yann-lty** [comment]
I'm totally okay with the MIT license. I'm not planning to work on qtsass anymore, so if adding the mail is mainly helpful for getting in touch with maintainers, it might be confusing. Anyway it's great to see this project coming back to life.

**Comment by danbradham** [comment]
Cool Yann, thanks for getting back to us. I've included your github url for recognition unless you'd like me to use your email. You have a point about future users attempting to get in touch with maintainers, we are including my email as current maintainer so hopefully that clarifies things.
